### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by lothid**
Support for Laravel 8.

### CODE REVIEW

**Comment by makasim** [comment]
Have you tested it with Laravel 8 ?

**Comment by lothid** [comment]
Yes, I am using it through my fork in Laravel 8 project.
Everything seems to work alright.
Not sure what to do with failed continuous-integration check though.

**Comment by danilopolani** [comment]
I guess the error of Travis comes from the tests on PHPv5.6 that does not support return types (or Type Hinting at all? I don't quite remember). Imho in a major of this package PHP5.6 should be deprecated and requiring only PHP >= 7.3 (Like Laravel 8) could be an idea. Not sure about PHP 7.3 as constraint, but it should be at least 7.1 IMHO

**Comment by makasim** [comment]
Could you please remove tests for PHP5.x version and raise a constraint to 7.1 ?

**Comment by lothid** [comment]
Sure.
In composer.json constraint is already PHP 7.1 so I just modified Travis CI PHP versions.

**Pull request merged**
