### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by snezhkoigor**
Support Laravel 7.x

### CODE REVIEW

**Comment by snezhkoigor** [comment]
@makasim Look this small changes please. I wanna install repo to my laravel 7 project. Thanks.

**Comment by snezhkoigor** [comment]
@makasim can you create tag for install from composer?

**Comment by makasim** [comment]
https://github.com/php-enqueue/laravel-queue/tree/0.10.2

**Comment by snezhkoigor** [comment]
@makasim great!

**Pull request merged**
